export const companies = [
  "Accenture",
  "Adobe",
  "Airtel",
  "Amazon",
  "American Express",
  "Apple",
  "Asian Paints",
  "Axis Bank",
  "Bajaj Finserv",
  "Bajaj Auto",
  "Bank of Baroda",
  "Bharti Airtel",
  "Biocon",
  "Bosch",
  "Byju's",
  "Capgemini",
  "Cognizant",
  "Colgate",
  "Deloitte",
  "Delhivery",
  "Flipkart",
  "Freshworks",
  "Google",
  "HCL",
  "HDFC Bank",
  "Hero MotoCorp",
  "HP",
  "IBM",
  "ICICI Bank",
  "Infosys",
  "Intel",
  "ITC",
  "Jio",
  "JP Morgan",
  "Larsen & Toubro",
  "Mahindra",
  "Microsoft",
  "Mindtree",
  "Nestle",
  "Netflix",
  "Oracle",
  "Paytm",
  "PhonePe",
  "PwC",
  "Reliance",
  "Salesforce",
  "Samsung",
  "Siemens",
  "Swiggy",
  "Tata Consultancy Services",
  "Tata Motors",
  "Tech Mahindra",
  "Tesla",
  "TCS",
  "Uber",
  "Unilever",
  "Vedanta",
  "Wipro",
  "Zomato",
];

for (let i = 1; i <= 440; i++) {
  companies.push(`Tech Company ${i}`);
}