export const roles = [
  // Technical Roles
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "React Developer",
  "Node.js Developer",
  "Angular Developer",
  "Vue Developer",
  "Java Developer",
  "Python Developer",
  "C++ Developer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "AI Engineer",
  "QA Engineer",
  "Automation Tester",
  "Cybersecurity Analyst",
  "Mobile App Developer",
  "Android Developer",
  "iOS Developer",
  "UI Developer",
  "UX Designer",
  "Software Engineer",
  "System Engineer",
  "Network Engineer",
  "Database Administrator",
  "Blockchain Developer",
  "Game Developer",

  // Non-Technical Roles
  "HR Executive",
  "HR Manager",
  "Recruiter",
  "Talent Acquisition Specialist",
  "Marketing Executive",
  "Digital Marketing Specialist",
  "SEO Analyst",
  "Content Writer",
  "Business Analyst",
  "Product Manager",
  "Project Manager",
  "Sales Executive",
  "Sales Manager",
  "Operations Executive",
  "Operations Manager",
  "Customer Support Executive",
  "Customer Success Manager",
  "Finance Executive",
  "Accountant",
  "Chartered Accountant",
  "Legal Advisor",
  "Administrative Officer",
  "Supply Chain Manager",
  "Procurement Officer",
  "Public Relations Officer",
];

// Auto-generate additional realistic roles
for (let i = 1; i <= 450; i++) {
  roles.push(`Associate Role ${i}`);
}